<a href="https://colab.research.google.com/github/asegura4488/EDCO_IntroCienciaDatos/blob/main/Semana4/LimpiezaExcel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
from google.colab import files
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

os.chdir('/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana3')
!ls

Datos				     Pandas_EstudioExploratorio.ipynb
PandasBasico_COVID_EDA_Modelo.ipynb  ProbabilidadKDE.ipynb

In [6]:
Database = pd.read_excel('Datos/Alcaceres.xlsx')
Database

,No,Subred,Localidad (NOMBRE),UPZ (Número),BARRIO (Nombre),Dirección,Nombre 1,Nombre 2,Apellido 1,Apellido 2,...,Observaciones.4,Fecha sesión 7,7. Sesión,Personas sesión 7,Observaciones.5,Fecha sesión 8,8. Sesión,Personas sesión 8,Observaciones.6,GRUPO AL QUE PERTENECE
0,1,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,DORIS,ANGELICA,BURITICA,BERMUDEZ,...,NaN,2022-08-23,AUTOCONOCIMIENTO,1,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,0,NaN,NaN
1,2,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,MARLENE,NaN,ACERO,CASALLAS,...,NaN,2022-08-23,AUTOCONOCIMIENTO,1,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,1,NaN,NaN
2,3,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,MARTHA,LUCIA,TORRES,NaN,...,NaN,2022-08-23,AUTOCONOCIMIENTO,1,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,1,NaN,NaN
3,4,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,CARMEN,ZENITH,GURDIOLA,NaN,...,NaN,2022-08-23,AUTOCONOCIMIENTO,1,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,0,NaN,NaN
4,5,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,ASENET,NaN,FLORES,PAREA,...,NaN,2022-08-23,AUTOCONOCIMIENTO,0,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,0,NaN,NaN
5,6,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,ANALUPE,NaN,SALINAS,NaN,...,NaN,2022-08-23,AUTOCONOCIMIENTO,0,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,0,NaN,NaN
6,7,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,YANIRA,NaN,MOYANO,BOHORQUEZ,...,NaN,2022-08-23,AUTOCONOCIMIENTO,0,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,0,NaN,NaN
7,8,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,CLAUDIA,NaN,MARTINEZ,CAMACHO,...,NaN,2022-08-23,AUTOCONOCIMIENTO,0,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,1,NaN,NaN
8,9,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,DENIS,MARCELA,CASTAÑEDA,NaN,...,NaN,2022-08-23,AUTOCONOCIMIENTO,0,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,1,NaN,NaN
9,10,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,ELVIRA,ESTHER,RODRIGUEZ,AROCHA,...,NaN,2022-08-23,AUTOCONOCIMIENTO,1,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,0,NaN,NaN
10,11,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,JAYDU,YAZMIN,ROA,DIAZ,...,NaN,2022-08-23,AUTOCONOCIMIENTO,1,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,0,NaN,NaN
11,12,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 79,ROSA,ISABEL,MARTINEZ,NaN,...,NaN,2022-08-23,AUTOCONOCIMIENTO,0,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,0,NaN,NaN
12,13,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 63,DORALBA,NaN,MARTINEZ,NaN,...,NaN,2022-08-23,AUTOCONOCIMIENTO,0,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,0,NaN,NaN
13,14,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 65,FABIAN,ALEXIS,TAPIA,PERDOMO,...,NaN,2022-08-23,AUTOCONOCIMIENTO,1,NaN,2022-08-25,DEPENDENCIA EMOCIONAL,1,NaN,NaN

In [7]:
# Que deberia hacer con los NAN de los nombre y apelldios
Database = Database.fillna("")
Database

,No,Subred,Localidad (NOMBRE),UPZ (Número),BARRIO (Nombre),Dirección,Nombre 1,Nombre 2,Apellido 1,Apellido 2,...,Observaciones.4,Fecha sesión 7,7. Sesión,Personas sesión 7,Observaciones.5,Fecha sesión 8,8. Sesión,Personas sesión 8,Observaciones.6,GRUPO AL QUE PERTENECE
0,1,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,DORIS,ANGELICA,BURITICA,BERMUDEZ,...,,2022-08-23,AUTOCONOCIMIENTO,1,,2022-08-25,DEPENDENCIA EMOCIONAL,0,,
1,2,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,MARLENE,,ACERO,CASALLAS,...,,2022-08-23,AUTOCONOCIMIENTO,1,,2022-08-25,DEPENDENCIA EMOCIONAL,1,,
2,3,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,MARTHA,LUCIA,TORRES,,...,,2022-08-23,AUTOCONOCIMIENTO,1,,2022-08-25,DEPENDENCIA EMOCIONAL,1,,
3,4,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,CARMEN,ZENITH,GURDIOLA,,...,,2022-08-23,AUTOCONOCIMIENTO,1,,2022-08-25,DEPENDENCIA EMOCIONAL,0,,
4,5,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,ASENET,,FLORES,PAREA,...,,2022-08-23,AUTOCONOCIMIENTO,0,,2022-08-25,DEPENDENCIA EMOCIONAL,0,,
5,6,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,ANALUPE,,SALINAS,,...,,2022-08-23,AUTOCONOCIMIENTO,0,,2022-08-25,DEPENDENCIA EMOCIONAL,0,,
6,7,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,YANIRA,,MOYANO,BOHORQUEZ,...,,2022-08-23,AUTOCONOCIMIENTO,0,,2022-08-25,DEPENDENCIA EMOCIONAL,0,,
7,8,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,CLAUDIA,,MARTINEZ,CAMACHO,...,,2022-08-23,AUTOCONOCIMIENTO,0,,2022-08-25,DEPENDENCIA EMOCIONAL,1,,
8,9,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,DENIS,MARCELA,CASTAÑEDA,,...,,2022-08-23,AUTOCONOCIMIENTO,0,,2022-08-25,DEPENDENCIA EMOCIONAL,1,,
9,10,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,ELVIRA,ESTHER,RODRIGUEZ,AROCHA,...,,2022-08-23,AUTOCONOCIMIENTO,1,,2022-08-25,DEPENDENCIA EMOCIONAL,0,,
10,11,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,JAYDU,YAZMIN,ROA,DIAZ,...,,2022-08-23,AUTOCONOCIMIENTO,1,,2022-08-25,DEPENDENCIA EMOCIONAL,0,,
11,12,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 79,ROSA,ISABEL,MARTINEZ,,...,,2022-08-23,AUTOCONOCIMIENTO,0,,2022-08-25,DEPENDENCIA EMOCIONAL,0,,
12,13,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 63,DORALBA,,MARTINEZ,,...,,2022-08-23,AUTOCONOCIMIENTO,0,,2022-08-25,DEPENDENCIA EMOCIONAL,0,,
13,14,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 65,FABIAN,ALEXIS,TAPIA,PERDOMO,...,,2022-08-23,AUTOCONOCIMIENTO,1,,2022-08-25,DEPENDENCIA EMOCIONAL,1,,

In [8]:
Database.keys()

Index(['No', 'Subred', 'Localidad (NOMBRE)', 'UPZ (Número)', 'BARRIO (Nombre)',
       'Dirección', 'Nombre 1', 'Nombre 2', 'Apellido 1', 'Apellido 2',
       'Tipo de Documento', 'Número de documento', 'Número de contacto 1',
       'Número de contacto 2', 'Canal de contacto', 'Genero',
       'Orientación Sexual', 'Fecha de nacimiento', 'Edad',
       'Etnia a la que pertenece', 'Pertenencia a grupo vulnerable',
       'Tipo de aseguramiento', 'A que EPS se encuentra afiliado',
       'Qué problemas de salud mental se han generado a causa de la Pandemia actual en el grupo',
       'VACUNA COVID-19', 'Fecha sesión 1',
       'Nombre del profesional que realizó intervención no presencial',
       '1. Sesión Lectura de necesidades - plan de acción',
       'Personas sesión 1', 'Observaciones concretas en caso necesario.',
       'Fecha sesión 2', '2. Sesión', 'Personas sesión 2', 'Observaciones',
       'Fecha sesión 3', '3. Sesión', 'Personas sesión 3', 'Observaciones.1',
       'Fecha sesión 4', '4. Sesión', 'Personas sesión 4', 'Observaciones.2',
       'Unnamed: 42', 'Fecha sesión 5', '5. Sesión', 'Personas sesión 5',
       'Observaciones.3', 'Fecha sesión 6', '6. Sesión', 'Personas sesión 6',
       'Observaciones.4', 'Fecha sesión 7', '7. Sesión', 'Personas sesión 7',
       'Observaciones.5', 'Fecha sesión 8', '8. Sesión', 'Personas sesión 8',
       'Observaciones.6', 'GRUPO AL QUE PERTENECE'],
      dtype='object')

In [12]:
NombreCompleto = Database['Apellido 1'] + " " + Database['Apellido 2'] + " " + Database['Nombre 1'] + " " + Database['Nombre 2']
NombreCompleto

0     BURITICA BERMUDEZ DORIS ANGELICA
1              ACERO CASALLAS MARLENE
2                 TORRES  MARTHA LUCIA
3              GURDIOLA  CARMEN ZENITH
4                 FLORES PAREA ASENET
5                    SALINAS  ANALUPE
6             MOYANO BOHORQUEZ YANIRA
7            MARTINEZ CAMACHO CLAUDIA
8             CASTAÑEDA  DENIS MARCELA
9       RODRIGUEZ AROCHA ELVIRA ESTHER
10               ROA DIAZ JAYDU YAZMIN
11               MARTINEZ  ROSA ISABEL
12                  MARTINEZ  DORALBA
13         TAPIA PERDOMO FABIAN ALEXIS
dtype: object

In [13]:
# Asignamos el nombre completo en algun lugar
Database.insert( loc=10, column='Nombre', value=NombreCompleto )

In [14]:
Database.iloc[:,:11]

,No,Subred,Localidad (NOMBRE),UPZ (Número),BARRIO (Nombre),Dirección,Nombre 1,Nombre 2,Apellido 1,Apellido 2,Nombre
0,1,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,DORIS,ANGELICA,BURITICA,BERMUDEZ,BURITICA BERMUDEZ DORIS ANGELICA
1,2,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,MARLENE,,ACERO,CASALLAS,ACERO CASALLAS MARLENE
2,3,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,MARTHA,LUCIA,TORRES,,TORRES MARTHA LUCIA
3,4,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,CARMEN,ZENITH,GURDIOLA,,GURDIOLA CARMEN ZENITH
4,5,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,ASENET,,FLORES,PAREA,FLORES PAREA ASENET
5,6,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,ANALUPE,,SALINAS,,SALINAS ANALUPE
6,7,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,YANIRA,,MOYANO,BOHORQUEZ,MOYANO BOHORQUEZ YANIRA
7,8,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,CLAUDIA,,MARTINEZ,CAMACHO,MARTINEZ CAMACHO CLAUDIA
8,9,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,DENIS,MARCELA,CASTAÑEDA,,CASTAÑEDA DENIS MARCELA
9,10,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,ELVIRA,ESTHER,RODRIGUEZ,AROCHA,RODRIGUEZ AROCHA ELVIRA ESTHER
10,11,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 67,JAYDU,YAZMIN,ROA,DIAZ,ROA DIAZ JAYDU YAZMIN
11,12,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 79,ROSA,ISABEL,MARTINEZ,,MARTINEZ ROSA ISABEL
12,13,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 63,DORALBA,,MARTINEZ,,MARTINEZ DORALBA
13,14,NORTE,BARRIOS UNIDOS,98,LOS ALCACERES,CRA 29A # 73 - 65,FABIAN,ALEXIS,TAPIA,PERDOMO,TAPIA PERDOMO FABIAN ALEXIS

In [15]:
# Cambiar le nombre de una columna
Database = Database.rename( columns={ 'Localidad (NOMBRE)' : 'Localidad' } )

In [17]:
Database.keys()

Index(['No', 'Subred', 'Localidad', 'UPZ (Número)', 'BARRIO (Nombre)',
       'Dirección', 'Nombre 1', 'Nombre 2', 'Apellido 1', 'Apellido 2',
       'Nombre', 'Tipo de Documento', 'Número de documento',
       'Número de contacto 1', 'Número de contacto 2', 'Canal de contacto',
       'Genero', 'Orientación Sexual', 'Fecha de nacimiento', 'Edad',
       'Etnia a la que pertenece', 'Pertenencia a grupo vulnerable',
       'Tipo de aseguramiento', 'A que EPS se encuentra afiliado',
       'Qué problemas de salud mental se han generado a causa de la Pandemia actual en el grupo',
       'VACUNA COVID-19', 'Fecha sesión 1',
       'Nombre del profesional que realizó intervención no presencial',
       '1. Sesión Lectura de necesidades - plan de acción',
       'Personas sesión 1', 'Observaciones concretas en caso necesario.',
       'Fecha sesión 2', '2. Sesión', 'Personas sesión 2', 'Observaciones',
       'Fecha sesión 3', '3. Sesión', 'Personas sesión 3', 'Observaciones.1',
       'Fecha sesión 4', '4. Sesión', 'Personas sesión 4', 'Observaciones.2',
       'Unnamed: 42', 'Fecha sesión 5', '5. Sesión', 'Personas sesión 5',
       'Observaciones.3', 'Fecha sesión 6', '6. Sesión', 'Personas sesión 6',
       'Observaciones.4', 'Fecha sesión 7', '7. Sesión', 'Personas sesión 7',
       'Observaciones.5', 'Fecha sesión 8', '8. Sesión', 'Personas sesión 8',
       'Observaciones.6', 'GRUPO AL QUE PERTENECE'],
      dtype='object')

In [18]:
Features = ['Tipo de Documento', \
            'Número de documento', \
            'Nombre', \
            'Número de contacto 1', \
            'A que EPS se encuentra afiliado', \
            'Localidad', \
            'Fecha sesión ', \
            'Personas sesión ']
Features

['Tipo de Documento',
 'Número de documento',
 'Nombre',
 'Número de contacto 1',
 'A que EPS se encuentra afiliado',
 'Localidad',
 'Fecha sesión ',
 'Personas sesión ']