<a href="https://colab.research.google.com/github/asegura4488/EDCO_IntroCienciaDatos/blob/main/Semana2/Sesion3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

In [2]:
# Librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# sistema operativo
import os

In [5]:
# llamar un camando de unix,linux. Directorio actual
# Comandos de ubicacion
!pwd

/content

In [4]:
"listar el contenido en la carpeta"
!ls

drive  sample_data

In [17]:
# Movernos de carpeta
ruta = "/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2"
os.chdir(ruta)

In [18]:
!ls

BaseDatos  Datos  Sesion3.ipynb

In [19]:
# Vamos a crear la carpeta de salida
salida = "Carpeta_salida"
os.makedirs(salida,exist_ok=True)

In [32]:
!pwd

/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida

In [29]:
#os.chdir(salida)

In [28]:
!pwd

/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida

In [31]:
# Como creamos 40 carpetas en la carpeta de salida????
for i in range(1,41):
  subcarpeta = 'sub_{}'.format(i)

  print('Creando carpeta:', subcarpeta)
  os.makedirs(subcarpeta, exist_ok = True)

Creando carpeta: sub_1
Creando carpeta: sub_2
Creando carpeta: sub_3
Creando carpeta: sub_4
Creando carpeta: sub_5
Creando carpeta: sub_6
Creando carpeta: sub_7
Creando carpeta: sub_8
Creando carpeta: sub_9
Creando carpeta: sub_10
Creando carpeta: sub_11
Creando carpeta: sub_12
Creando carpeta: sub_13
Creando carpeta: sub_14
Creando carpeta: sub_15
Creando carpeta: sub_16
Creando carpeta: sub_17
Creando carpeta: sub_18
Creando carpeta: sub_19
Creando carpeta: sub_20
Creando carpeta: sub_21
Creando carpeta: sub_22
Creando carpeta: sub_23
Creando carpeta: sub_24
Creando carpeta: sub_25
Creando carpeta: sub_26
Creando carpeta: sub_27
Creando carpeta: sub_28
Creando carpeta: sub_29
Creando carpeta: sub_30
Creando carpeta: sub_31
Creando carpeta: sub_32
Creando carpeta: sub_33
Creando carpeta: sub_34
Creando carpeta: sub_35
Creando carpeta: sub_36
Creando carpeta: sub_37
Creando carpeta: sub_38
Creando carpeta: sub_39
Creando carpeta: sub_40

In [37]:
# Veamos nuestras bases
BaseDatos = {
    101: {'Nombre':'Andres','Apellido':'Trujillo','Edad': 35,'Genero': 'M' },
    102: {'Nombre':'Diana','Apellido':'Henao','Edad': 25,'Genero': 'F' },
    103: {'Nombre':'Javier','Apellido':'Bastidas','Edad': 22,'Genero': 'M' }
}

In [38]:
#Primer dataframe
df = pd.DataFrame.from_dict(BaseDatos,orient='index')
df

     Nombre  Apellido  Edad Genero
101  Andres  Trujillo    35      M
102   Diana     Henao    25      F
103  Javier  Bastidas    22      M

In [40]:
# Elegir una columna de los datos
df['Edad']

101    35
102    25
103    22
Name: Edad, dtype: int64

In [41]:
# Pandas basico
df.index.name = 'ID'
df

     Nombre  Apellido  Edad Genero
ID
101  Andres  Trujillo    35      M
102   Diana     Henao    25      F
103  Javier  Bastidas    22      M

In [42]:
# POdemos convertir el ID en una columna
df = df.reset_index()
df

    ID  Nombre  Apellido  Edad Genero
0  101  Andres  Trujillo    35      M
1  102   Diana     Henao    25      F
2  103  Javier  Bastidas    22      M

In [44]:
# Visualizar los dataframe
df.head(2)

    ID  Nombre  Apellido  Edad Genero
0  101  Andres  Trujillo    35      M
1  102   Diana     Henao    25      F

In [47]:
# La dimension de la matriz
df.shape

(3, 5)

In [48]:
df

    ID  Nombre  Apellido  Edad Genero
0  101  Andres  Trujillo    35      M
1  102   Diana     Henao    25      F
2  103  Javier  Bastidas    22      M

In [49]:
# Como consultamos el nombre las columnas
df.keys()

Index(['ID', 'Nombre', 'Apellido', 'Edad', 'Genero'], dtype='object')

In [50]:
df.columns

Index(['ID', 'Nombre', 'Apellido', 'Edad', 'Genero'], dtype='object')

In [52]:
# Consultar los tipos
df.dtypes

ID           int64
Nombre      object
Apellido    object
Edad         int64
Genero      object
dtype: object

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        3 non-null      int64
 1   Nombre    3 non-null      object
 2   Apellido  3 non-null      object
 3   Edad      3 non-null      int64
 4   Genero    3 non-null      object
dtypes: int64(2), object(3)
memory usage: 252.0+ bytes

In [55]:
df.describe()

          ID       Edad
count    3.0   3.000000
mean   102.0  27.333333
std      1.0   6.806859
min    101.0  22.000000
25%    101.5  23.500000
50%    102.0  25.000000
75%    102.5  30.000000
max    103.0  35.000000

In [57]:
# Quremos escoger unas columnas especificas
df1 = df[['Edad','Genero']]
df1

   Edad Genero
0    35      M
1    25      F
2    22      M

In [60]:
# Aplicar mascarcaras "masking" o filtros
# Personas mayores a 25
mask = df['Edad'] >= 25 # Esto es una condición
mask

0     True
1     True
2    False
Name: Edad, dtype: bool

In [61]:
df2 = df[mask]
df2

    ID  Nombre  Apellido  Edad Genero
0  101  Andres  Trujillo    35      M
1  102   Diana     Henao    25      F

In [62]:
mask2 = df['Genero'] == 'M'
mask2

0     True
1    False
2     True
Name: Genero, dtype: bool

In [64]:
df3 = df[mask2]
df3

    ID  Nombre  Apellido  Edad Genero
0  101  Andres  Trujillo    35      M
2  103  Javier  Bastidas    22      M

In [67]:
df

    ID  Nombre  Apellido  Edad Genero
0  101  Andres  Trujillo    35      M
1  102   Diana     Henao    25      F
2  103  Javier  Bastidas    22      M

In [68]:
# filtro es que tenga 25 años o más
# filtro es que sea del genero masculino
df[mask & mask2]

    ID  Nombre  Apellido  Edad Genero
0  101  Andres  Trujillo    35      M

In [69]:
df[mask | mask2]

    ID  Nombre  Apellido  Edad Genero
0  101  Andres  Trujillo    35      M
1  102   Diana     Henao    25      F
2  103  Javier  Bastidas    22      M